cmake_minimum_required(VERSION 3.22)
project(reflect_demo LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
add_library(native_app_glue STATIC ${ANDROID_NDK}/sources/android/native_app_glue/android_native_app_glue.c)
target_include_directories(native_app_glue PUBLIC ${ANDROID_NDK}/sources/android/native_app_glue)
add_library(reflect_demo SHARED demo.cpp)
target_include_directories(reflect_demo PRIVATE ${OPENXR_LOADER_DIR}/prefab/modules/headers/include)
target_link_libraries(reflect_demo PRIVATE native_app_glue ${OPENXR_LOADER_DIR}/jni/arm64-v8a/libopenxr_loader.so EGL GLESv3 android log)
target_link_options(reflect_demo PRIVATE -u ANativeActivity_onCreate)
