"""Compiles android-runtime/shaders/*.comp to SPIR-V headers (android-runtime/shaders/<name>.spv.h).

The generated headers are checked in, so the runtime build does not need glslc.
Usage: python tools/compile_shaders.py [path/to/glslc]
"""
import glob
from pathlib import Path
import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    state = Path(os.environ.get("REFLECT_HOME", Path.home() / "Library/Application Support/Reflect"))
    sdk = Path(os.environ.get("ANDROID_HOME", state / "sdk"))
    glslc = sys.argv[1] if len(sys.argv) > 1 else str(sdk / "ndk/27.3.13750724/shader-tools/darwin-x86_64/glslc")
    for source in glob.glob(os.path.join(ROOT, "android-runtime", "shaders", "*.comp")):
        name = os.path.splitext(os.path.basename(source))[0]
        with tempfile.TemporaryDirectory() as temp:
            spv = os.path.join(temp, name + ".spv")
            subprocess.run([glslc, "-O", "--target-env=vulkan1.0", "-o", spv, source], check=True)
            data = open(spv, "rb").read()
        words = struct.unpack("<%dI" % (len(data) // 4), data)
        lines = [", ".join("0x%08x" % w for w in words[i:i + 8]) for i in range(0, len(words), 8)]
        header = os.path.join(ROOT, "android-runtime", "shaders", name + ".spv.h")
        with open(header, "w", newline="\n") as out:
            out.write("// Generated by tools/compile_shaders.py from %s.comp; do not edit.\n#pragma once\n#include <cstdint>\n" % name)
            out.write("constexpr uint32_t k_%s_spv[] = {\n    %s,\n};\n" % (name, ",\n    ".join(lines)))
        print("%s: %d words -> %s" % (name, len(words), header))


if __name__ == "__main__":
    main()
