"""Compiles tools/shaders/astc_bc3.comp into macos/vulkan-compat/astc_bc3_spirv.h (SPIR-V words for the Android Vulkan layer).

Adds the BC1 single-colour tables (texture_transcode.h SingleColorTable) to the shader first.
Usage: python tools/gen_astc_bc3_shader.py [path to glslc]  (default: the NDK's shader-tools glslc)
"""
from pathlib import Path
import os
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
MARKER = '// SINGLE_COLOR_TABLES'


def single_color_table(levels, expand):
    table = []
    for v in range(256):
        best, pair = 1 << 30, (0, 0)
        for a in range(levels):
            for b in range(levels):
                err = abs((2 * expand(a) + expand(b)) // 3 - v) * 4 + abs(a - b)
                if err < best:
                    best, pair = err, (a, b)
        table.append(pair[0] | pair[1] << 8)
    return table


def glsl_array(name, values):
    rows = [', '.join(f'{v}u' for v in values[i:i + 16]) for i in range(0, len(values), 16)]
    return f'const uint {name}[256] = uint[](\n    ' + ',\n    '.join(rows) + ');\n'


def main():
    state = Path(os.environ.get("REFLECT_HOME", Path.home() / "Library/Application Support/Reflect"))
    sdk = Path(os.environ.get("ANDROID_HOME", state / "sdk"))
    glslc = sys.argv[1] if len(sys.argv) > 1 else str(sdk / "ndk/27.3.13750724/shader-tools/darwin-x86_64/glslc")
    source = open(os.path.join(HERE, 'shaders', 'astc_bc3.comp'), encoding='utf-8').read()
    five = single_color_table(32, lambda v: v << 3 | v >> 2)
    six = single_color_table(64, lambda v: v << 2 | v >> 4)
    lines = source.split('\n')
    at = next(i for i, line in enumerate(lines) if line.startswith(MARKER))
    lines[at] = glsl_array('kFive', five) + glsl_array('kSix', six)
    with tempfile.TemporaryDirectory() as tmp:
        comp, spv = os.path.join(tmp, 'astc_bc3.comp'), os.path.join(tmp, 'astc_bc3.spv')
        open(comp, 'w', encoding='utf-8').write('\n'.join(lines))
        subprocess.run([glslc, '-O', '--target-env=vulkan1.0', '-fshader-stage=compute', comp, '-o', spv], check=True)
        code = open(spv, 'rb').read()
    words = struct.unpack(f'<{len(code) // 4}I', code)
    body = ',\n'.join('    ' + ', '.join(f'0x{w:08x}' for w in words[i:i + 8]) for i in range(0, len(words), 8))
    out = os.path.join(HERE, '..', 'macos', 'vulkan-compat', 'astc_bc3_spirv.h')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by tools/gen_astc_bc3_shader.py from tools/shaders/astc_bc3.comp. Do not edit.\n')
        f.write('#pragma once\n#include <cstdint>\n\nnamespace refract::shaders {\n')
        f.write(f'inline constexpr uint32_t kAstcBc3[{len(words)}] = {{\n{body}}};\n}}  // namespace refract::shaders\n')
    print(f'{out}: {len(words)} words')


if __name__ == '__main__':
    main()
